#swagger.title=spring-boot-starter-swagger
#swagger.description=Starter for swagger 2.x
#swagger.version=1.4.0.RELEASE
#swagger.license=Apache License, Version 2.0
#swagger.licenseUrl=https://www.apache.org/licenses/LICENSE-2.0.html
#swagger.termsOfServiceUrl=https://github.com/dyc87112/spring-boot-starter-swagger
#swagger.contact.name=liwenrui
#  #swagger.contact.url=http://blog.didispace.com
#swagger.contact.email=358633069@qq.com
#swagger.base-package=com.rb
#swagger.base-path=/**
#
#
#spring.datasource.druid.url=jdbc:mysql://localhost:3306/liwenruidb
#spring.datasource.druid.username=root
#spring.datasource.druid.password=Aa12345678
#spring.datasource.druid.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.druid.initialSize=10
#spring.datasource.druid.maxActive=20
#spring.datasource.druid.maxWait=60000
#spring.datasource.druid.minIdle=1
#spring.datasource.druid.timeBetweenEvictionRunsMillis=60000
#spring.datasource.druid.minEvictableIdleTimeMillis=300000
#spring.datasource.druid.testWhileIdle=true
#spring.datasource.druid.testOnBorrow=true
#spring.datasource.druid.testOnReturn=false
#spring.datasource.druid.poolPreparedStatements=true
#spring.datasource.druid.maxOpenPreparedStatements=20
#spring.datasource.druid.validationQuery=SELECT 1
#spring.datasource.druid.validation-query-timeout=500
#spring.datasource.druid.filters=stat

#server:
#  port: 8080
#  servlet:
#    context-path: /
spring:
  datasource:
    username: root
    password: Aa12345678
    url: jdbc:mysql://localhost:3306/liwenruidb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
